[features]
seeds = false
skip-lint = false
[programs.localnet]
authority = "5CwdMJAonGG6ESBqWZtRNbPBe5ZzgnqCg5itB4vqydFu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/nhatminhphan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
